In [12]:
!pip install -qq pandas numpy pyarrow

# Objetivo

El objetivo de este notebook es crear nuevas variables derivadas de los datos originales, con el fin de poder capturar mejor las características relevantes de los inmuebles

Se crearon las siguientes variables:

* price_per_m2: Precio por metro cuadrado
* total_surface: Área de construcción  + Área de terreno
* age: Edad del inmueble = 2025 - built_year
* has_amenities: Si tiene gym o jardín
* type_apartment: 1 es apartamento, 0 es casa 
* type_house: 1 es casa, 0 es apartamento
* neigh_{nombre_colonia}: tenemos n variables por cada valor único de colonia, 1 te indica si es esa colonia, de lo contrario es 0

    i.e neigh_CONDESA = 1 significa que ese inmueble está en la condesa

In [4]:
import pandas as pd

In [5]:
df = pd.read_parquet("../data/interim/cleaned.parquet")

In [6]:
import sys
from pathlib import Path

project_root = Path().resolve().parent
sys.path.append(str(project_root))

In [7]:
from dd360.features import engineer_features

In [8]:
final_df = engineer_features(df)

In [9]:
final_df.head()

,property_id,listing_type,property_type,url_ad,price,terrain_surface,construction_surface,num_bathrooms,num_parking_lots,num_bedrooms,...,neigh_ROMA SUR,neigh_SAN RAFAEL,neigh_SAN SIMON TOLNAHUAC,neigh_SANTA MARIA INSURGENTES,neigh_SANTA MARIA LA RIBERA,neigh_TABACALERA,neigh_TRANSITO,neigh_UNIDAD HAB NONOALCO TLATELOLCO,neigh_VALLE GOMEZ,neigh_VISTA ALEGRE
0,5ae456983ab717ec68e1ff2e0689c5d8,for-sale,apartment,https://rentahouse.com.mx/departamento_en_vent...,9348347.0,260.0,96.0,2,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,fff8db1482a59a1c9093f9ab3ac50ddf,for-sale,apartment,https://www.easybroker.com/mx/listings/departa...,16200000.0,244.5,90.0,2,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,7f0478d4f668aaf45ed3511523746fce,for-sale,apartment,https://www.vivanuncios.com.mx/a-venta-departa...,5400000.0,244.5,110.0,1,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4a0034cf7bfdd9b610bcb4a2e5096cf0,for-sale,apartment,https://www.clau.com/propiedades/3pm-departame...,6700000.0,194.5,79.0,2,0,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,afdc70d7a521ba91cc026062653fe841,for-sale,apartment,https://degohouse.com.mx/apartamento-venta-non...,3778408.0,200.0,67.0,2,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4513 entries, 0 to 4512
Data columns (total 58 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   property_id                           4513 non-null   object
 1   listing_type                          4513 non-null   object
 2   property_type                         4513 non-null   object
 3   url_ad                                4513 non-null   object
 4   price                                 4513 non-null   float64
 5   terrain_surface                       4513 non-null   float64
 6   construction_surface                  4513 non-null   float64
 7   num_bathrooms                         4513 non-null   int64
 8   num_parking_lots                      4513 non-null   int64
 9   num_bedrooms                          4513 non-null   int64
 10  built_year                            4513 non-null   int64
 11  conservation_status                   4513 non-null   float64
 12  latitude                              4513 non-null   float64
 13  longitude                             4513 non-null   float64
 14  id_neighborhood                       4513 non-null   int64
 15  neighborhood                          4513 non-null   object
 16  has_garden                            4513 non-null   int64
 17  has_gym                               4513 non-null   int64
 18  price_per_m2                          4513 non-null   float64
 19  total_surface                         4513 non-null   float64
 20  age                                   4513 non-null   int64
 21  has_amenities                         4513 non-null   int64
 22  type_apartment                        4513 non-null   float64
 23  type_house                            4513 non-null   float64
 24  neigh_ALGARIN                         4513 non-null   float64
 25  neigh_AMPL ASTURIAS                   4513 non-null   float64
 26  neigh_ASTURIAS                        4513 non-null   float64
 27  neigh_ATLAMPA                         4513 non-null   float64
 28  neigh_BUENAVISTA                      4513 non-null   float64
 29  neigh_BUENOS AIRES                    4513 non-null   float64
 30  neigh_CENTRO                          4513 non-null   float64
 31  neigh_CENTRO URBANO BENITO JUAREZ     4513 non-null   float64
 32  neigh_CONDESA                         4513 non-null   float64
 33  neigh_CUAUHTEMOC                      4513 non-null   float64
 34  neigh_DOCTORES                        4513 non-null   float64
 35  neigh_ESPERANZA                       4513 non-null   float64
 36  neigh_EX HIPODROMO DE PERALVILLO      4513 non-null   float64
 37  neigh_FELIPE PESCADOR                 4513 non-null   float64
 38  neigh_GUERRERO                        4513 non-null   float64
 39  neigh_HIPODROMO                       4513 non-null   float64
 40  neigh_HIPODROMO DE LA CONDESA         4513 non-null   float64
 41  neigh_JUAREZ                          4513 non-null   float64
 42  neigh_MAZA                            4513 non-null   float64
 43  neigh_MORELOS                         4513 non-null   float64
 44  neigh_OBRERA                          4513 non-null   float64
 45  neigh_PAULINO NAVARRO                 4513 non-null   float64
 46  neigh_PERALVILLO                      4513 non-null   float64
 47  neigh_ROMA NORTE                      4513 non-null   float64
 48  neigh_ROMA SUR                        4513 non-null   float64
 49  neigh_SAN RAFAEL                      4513 non-null   float64
 50  neigh_SAN SIMON TOLNAHUAC             4513 non-null   float64
 51  neigh_SANTA MARIA INSURGENTES         4513 non-null   float64
 52  neigh_SANTA MARIA LA RIBERA           4513 non-null   float64
 53  neigh_TABACALERA                      4513 non-null   float64
 54  neigh_TRANSITO                        4513 non-null   float64
 55  neigh_UNIDAD HAB NONOALCO TLATELOLCO  4513 non-null   float64
 56  neigh_VALLE GOMEZ                     4513 non-null   float64
 57  neigh_VISTA ALEGRE                    4513 non-null   float64
dtypes: float64(44), int64(9), object(5)
memory usage: 2.0+ MB

In [11]:
final_df.to_parquet('../data/processed/final_df.parquet', index = False)